[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'

solc-version = "0.8.28"
optimizer = true
optimizer-runs = 10_000_000
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "euler-price-oracle/=lib/euler-price-oracle/src/",
    "@pendle/core-v2/=lib/pendle-core-v2-public/contracts/",
]
